### ISSUE TITLE
Azure Resources API v2

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#390]
**Resource Groups**
- [x] Workspace view @philliphoff #388 9/30
	- [x] Workspace compatibility shim @alexweininger https://github.com/microsoft/vscode-azureresourcegroups/pull/398
- [x] Tree item ID format @philliphoff 10/06 https://github.com/microsoft/vscode-azureresourcegroups/pull/401
	- [x] Make TreeItem ids follow Azure ids @alexweininger
	- [x] Find tree item @bwateratmsft ~10/10~ 11/09 @alexweininger
	- [x] #479
- [ ] #391 @bwateratmsft 11/14
	- [ ] Implementation @bwateratmsft ~10/06~ 11/14 https://github.com/microsoft/vscode-azureresourcegroups/pull/395
- [x] Azure Resources commands
	- [x] View Properties @alexweininger https://github.com/microsoft/vscode-azureresourcegroups/pull/427 ~10/12~ 11/14
	- [x] Open in Portal @philliphoff ~10/12~ 11/14 https://github.com/microsoft/vscode-azureresourcegroups/pull/419
- [x] Make resource types show up regardless of if resources of those types exist on the subscription @alexweininger investigate
- [ ] #464  @alexweininger
- [x] Group by... command @alexweininger #465 #517 
- [x] Remove `revealTreeItem` from API. It was only used by RGs, and now it's not used at all. https://github.com/microsoft/vscode-azureresourcegroups/pull/457
- [x] Add register activity API to V2 API (to prevent extensions from using both V1 & V2)
- [x] Remove V1 related views and code
- [x] Final review of API surface, package.json contributes schema, naming, parameter definitions, etc 

**v1.5 Client Compatibility**
- [x] Resolver compatibility shim @alexweininger @bwateratmsft 9/28
	- [x] #358 
	- [x] #381 
- [x] Open in portal
- [x] View properties
- [x] `pickAppResource` compatibility shim @alexweininger #382 9/30
- [x] `findTreeItem`
- [x] `reveal`

**Utils**
- [x] Pick tree item wizard core @alexweininger @bwateratmsft  https://github.com/microsoft/vscode-azuretools/pull/1229
	- [x] compat steps @alexweininger https://github.com/microsoft/vscode-azuretools/pull/1235
	- [x] Back button support for tree item picker via wizard step undo * @alexweininger 11/03 https://github.com/microsoft/vscode-azuretools/pull/1241
- [x] `registerCommand` compatibility shim @bwateratmsft 10/12
	- [x] Wrap/Unwrap @bwateratmsft 
- [x] Move API v2 type definitions to permanent location ~10/12~ 11/14 https://github.com/microsoft/vscode-azuretools/pull/1294

\* won't result in regression if omitted from initial release

**Client extensions v1.5 migration (7 extensions)** Start work on client extensions by 10/12
- [x] Write guide for upgrading client extensions for API v2 compatibility @alexweininger 10/12 https://github.com/microsoft/vscode-azureresourcegroups/wiki/Upgrading-Extensions-for-V2-Compatibility
- [ ] Upgrade extensions for Azure Resources API v2 compatibility 10/21
    - [ ] Functions @alexweininger
    - [x] App Service @motm32 https://github.com/microsoft/vscode-azureappservice/pull/2325
    - [x] Static Web Apps @MicroFish91 
    - [x] Container Apps @MicroFish91 
    - [x] Storage @alexweininger
    - [x] Databases @motm32 
    - [x] Virtual Machines @motm32 https://github.com/microsoft/vscode-azurevirtualmachines/pull/351

**v1.5 extension testing**
- [x] Virtual Machines - target release 01/25
	- [x] backward - CTI
	- [x] forward - @alexweininger
- [x] Static Web Apps - target release 01/25
	- [x] backward - CTI
	- [x] forward - @motm32 
- [x] App Service - target release 02/08
	- [x] backward - CTI
	- [x] forward - @MicroFish91 
- [x] Storage - target release 02/08
	- [x] backward
	- [x] forward - @motm32
- [x] Databases - target release 02/15
	- [x] backward - CTI
	- [x] forward
- [x] Functions - target release 02/15
	- [x] backward - CTI
	- [x] forward

Resource Groups v2 - 02/22

**v2 testing**
- [x] Container Apps v2 rewrite @alexweininger
- [x] Resource Groups v2 API

**Pre release admin tasks**
- [x] Write documentation for Azure Resources API v2 @alexweininger
	- [x] Overview and Integration guide
- [x] Update walkthrough
- [ ] Notify docs team of any relevant changes @alexweininger 
- [ ] Write sample/test extension that exercises the Azure Resources API v2
